version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: taxi24_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taxi24
    volumes:
      - taxi24_pg_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - taxi24_net

  api:
    build: .
    container_name: taxi24_api
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: taxi24
      NODE_ENV: development
    networks:
      - taxi24_net
    command: npm run start:prod

volumes:
  taxi24_pg_data:

networks:
  taxi24_net: